Update Pipeline_Logs

diff --git a/Pipeline_Logs b/Pipeline_Logs
--- a/Pipeline_Logs
+++ b/Pipeline_Logs
@@ -1,49 +1,70 @@
-[osuser@bastion ~]$ oc get kafkanodepool controller -n dev-kafka -o yaml
-apiVersion: kafka.strimzi.io/v1beta2
-kind: KafkaNodePool
-metadata:
-  annotations:
-    argocd.argoproj.io/sync-wave: "8"
-    meta.helm.sh/release-name: epay-common
-    meta.helm.sh/release-namespace: dev-epay-common
-  creationTimestamp: "2025-11-11T09:58:35Z"
-  generation: 2
-  labels:
-    app.kubernetes.io/component: kafka-controller
-    app.kubernetes.io/instance: epay-common
-    app.kubernetes.io/managed-by: Helm
-    app.kubernetes.io/name: controller
-    environment: dev
-    strimzi.io/cluster: dev-kafka-cluster
-  name: controller
-  namespace: dev-kafka
-  resourceVersion: "496872266"
-  uid: 0d449a5b-2388-4876-9352-4097f18b6ad2
-spec:
-  replicas: 3
-  roles:
-  - controller
-  storage:
-    type: jbod
-    volumes:
-    - deleteClaim: false
-      id: 0
-      kraftMetadata: shared
-      size: 100Gi
-      type: persistent-claim
-  template:
-    kafkaContainer: {}
-    pod:
-      terminationGracePeriodSeconds: 120
-status:
-  clusterId: 3aEx1xmUSTWs8xSplBnYtA
-  conditions: []
-  labelSelector: strimzi.io/cluster=dev-kafka-cluster,strimzi.io/name=dev-kafka-cluster-kafka,strimzi.io/kind=Kafka,strimzi.io/pool-name=controller
-  nodeIds:
-  - 3
-  - 4
-  - 5
-  observedGeneration: 2
-  replicas: 3
-  roles:
-  - controller
+.fortify_scan:
+  image: artifactory.jfrog.sbi:443/dso-base-image/ubi9/ubi9-java21-fortify-24.4:2.0
+  stage: fortify_scan
+  tags:
+    - common_runner
+  before_script:
+    - |
+      keytool -import -alias jfrog-artifactory -file "$ARTIFACTORY_CERT" \
+        -keystore /home/default/custom-truststore.jks -storepass changeit -noprompt
+      export MAVEN_OPTS="${MAVEN_OPTS} \
+        -Djavax.net.ssl.trustStore=/home/default/custom-truststore.jks \
+        -Djavax.net.ssl.trustStorePassword=changeit"
+  script:
+    - sourceanalyzer -clean -b $CI_PROJECT_PATH_SLUG
+    - sourceanalyzer -b $CI_PROJECT_PATH_SLUG
+        mvn $MAVEN_CLI_OPTS clean compile -U -DskipTests=true
+        -Dfortify.sca.exclude=target
+    - sourceanalyzer -b $CI_PROJECT_PATH_SLUG -scan -Xmx${FORTIFY_MEM} -f ${CI_PROJECT_PATH_SLUG}.fpr
+    - BIRTReportGenerator -template "Developer Workbook"
+        -source ${CI_PROJECT_PATH_SLUG}.fpr
+        -format pdf -output ${CI_PROJECT_PATH_SLUG}_report.pdf
+    - FPRUtility -information -search
+        -query "[fortify priority order]:critical OR [fortify priority order]:high"
+        -project ${CI_PROJECT_PATH_SLUG}.fpr > sca_gate.txt
+    - ISSUES=$(grep -i "matched search query" sca_gate.txt | awk '{print $1}')
+    - |
+      if [ -n "$ISSUES" ] && [ "$ISSUES" -gt 0 ]; then
+        echo -e "\e[31m=========================================\e[0m"
+        echo -e "\e[31m QUALITY GATE FAILED\e[0m"
+        echo -e "\e[31mHigh/Critical Vulnerabilities: $ISSUES\e[0m"
+        echo -e "\e[31m=========================================\e[0m"
+        exit 1
+      else
+        echo -e "\e[32m=========================================\e[0m"
+        echo -e "\e[32m QUALITY GATE PASSED\e[0m"
+        echo -e "\e[32mHigh/Critical Vulnerabilities: 0\e[0m"
+        echo -e "\e[32m=========================================\e[0m"
+      fi
+  artifacts:
+    paths:
+      - ${CI_PROJECT_PATH_SLUG}_report.pdf
+      - ${CI_PROJECT_PATH_SLUG}_report.xml
+      - ${CI_PROJECT_PATH_SLUG}.fpr
+    expire_in: 1 day
+    when: always
+  allow_failure: true
+
+.fortifytoGitlab:
+    stage: fortify_scan
+    tags:
+      - common_runner
+    needs:
+      - fortify_scan  
+
+    before_script:
+      - git config --global http.sslVerify false
+    image: artifactory.jfrog.sbi:443/dso-docker-base-images/py-fortify:0.0.1
+    script:
+      - echo ${CLONE_TOKEN}
+      - git clone https://oauth2:${CLONE_TOKEN}@gitlab.sbi/centraliseddevsecops/common-utility/utility.git
+      - ls -ltrh
+      - python3 utility/script/fortify_to_gitlab.py ${CI_PROJECT_PATH_SLUG}.fpr
+    artifacts:
+      reports:
+        sast: gl-sast-report.json
+      paths:
+        - gl-sast-report.json
+        - ${CI_PROJECT_PATH_SLUG}.fpr
+
+ 
